blank_issues_enabled: false
contact_links:
  - name: Aquarius Discord Server
    url: https://discord.companyinc.company
    about: If you have a question or need support, feel free to join our Discord and ask there!
