name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Digital Ocean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configure Environmental Variables
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENTRY: ${{ secrets.SENTRY }}
          DICTIONARY_API_KEY: ${{ secrets.DICTIONARY_API_KEY }}
          TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          HEARTHSTONE_KEY: ${{ secrets.HEARTHSTONE_KEY }}
          SHOWTIMES_SERVER: ${{ secrets.SHOWTIMES_SERVER }}
          SHOWTIMES_KEY: ${{ secrets.SHOWTIMES_KEY }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          DARK_SKY_API_KEY: ${{ secrets.DARK_SKY_API_KEY }}
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          FINANCIAL_MODELING_API_KEY: ${{ secrets.FINANCIAL_MODELING_API_KEY }}
          IQAIR_API_KEY: ${{ secrets.IQAIR_API_KEY }}
          LOGDNA_KEY: ${{ secrets.LOGDNA_KEY }}
        run: envsubst < $GITHUB_WORKSPACE/app.yml > $GITHUB_WORKSPACE/do_app.yml

      - name: Apply Database Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Reconfigure DigitalOcean App
        env:
          APP_ID: ${{ secrets.APP_ID }}
        run: doctl apps update $APP_ID --spec $GITHUB_WORKSPACE/do_app.yml

      - name: Deploy to DigitalOcean
        env:
          APP_ID: ${{ secrets.APP_ID }}
        run: doctl apps create-deployment $APP_ID --wait=true

      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: Aquarius has been redeployed
